package ethdev

type TxOffloadCap uint64

const (
	TxOffloadCapVLANInsert TxOffloadCap = 1 << iota
	TxOffloadCapIPv4Checksum
	TxOffloadCapUDPChecksum
	TxOffloadCapTCPChecksum
	TxOffloadCapSCTPChecksum
	TxOffloadCapTCPTSO
	TxOffloadCapUDPTSO
	TxOffloadCapOuterIPv4Checksum
	TxOffloadCapQINQInsert
	TxOffloadCapVXLANTunnelTSO
	TxOffloadCapGRETunnelTSO
	TxOffloadCapIPIPTunnelTSO
	TxOffloadCapGENEVETunnelTSO
	TxOffloadCapMACSECInsert
	TxOffloadCapMTLockFree
	TxOffloadCapMultiSegs
	TxOffloadCapMbufFastFree
	TxOffloadCapSecurity
	TxOffloadCapUDPTunnelTSO
	TxOffloadCapIPTunnelTSO
	TxOffloadCapOuterUDPChecksum
	TxOffloadCapSendOnTimestamp
)
